# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d6f0c416b146ed45b448680d760042770238fbddca53c6f359c8111f0d28f3c041b281617a84a46bfca01a2a1ca5d02778bf294e52619b3a131ebb96bb359884

test:
  secret_key_base: 6b42f54935e1fc485a4b79ad85f0cde5be9bf4116475bd4a848d0077200e6b20242299c4d530b9c2874a689243e9772ddbb01497e28a1e1aefc0c9e7176033f5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
